### ISSUE TITLE
where moni

### ISSUE THREAD

**Issue by HARDIntegral** [Okirshen/Plzgibme#1]

**Comment by Okirshen** [comment]
Hello, we are sorry to hear about this misunderstanding.
as the unwritten Terms of Service say:

> 100% of all income will go to plzgibme and son, the other 0% will be sent to the owner of the fund after the goal has been reached

If you want further support to direct message us at @plzgibme on [twitter](https://twitter.com/fuckoff) and good luck on your usage of our service 🤪

**Comment by HARDIntegral** [comment]
wait a minute

**Comment by Okirshen** [comment]
To further explain we are an open charity with 90$ of the income going to help the needed we pay only the little bits left to our owner and staff

p.s.o a yacht can help the needed

**Comment by HARDIntegral** [comment]
i dont have a yacht small enough to donate
